mainTableCombined <- read.csv('C:/Users/sec/Desktop/GDP_AFRICA.csv', stringsAsFactors = F)
str(mainTableCombined)
library('plm')
pdata <- pdata.frame(mainTableCombined, index = c('country', 'Time'))
colnames(mainTableCombined)
fixedGrowthGDPs <- plm(GDP_growth ~ ODA_growth + FDI_growth + EXP_growth  + GOV_growth + CSK_growth+ POP_growth + GOV_growth+ GDP_growth_LAG, data=pdata, model= "within")
fixedGrowthTFPs <- plm(TFP_growth ~ ODA_growth + FDI_growth + EXP_growth+GOV_growth+GDP_growth_LAG, data=pdata, model= "within")
fixedGrowthLagGDP <- plm(GDP_growth ~ ODA_growth + FDI_growth + EXP_growth + GOV_growth + CSK_growth + POP_growth + GDP_growth_LAG+ ODA_growth_LAG+ FDI_growth_LAG + EXP_growth_LAG + GOV_growth_LAG  + CSK_growth_LAG+ POP_growth_LAG, data=pdata, model= "within")
fixedGrowthLagTFP <- plm(TFP_growth ~ ODA_growth + FDI_growth + EXP_growth + GOV_growth + GDP_growth_LAG + ODA_growth_LAG+ FDI_growth_LAG + EXP_growth_LAG + GOV_growth_LAG, data=pdata, model= "within")
library(texreg)
htmlreg(list(fixedGrowthGDPs, fixedGrowthTFPs, fixedGrowthLagGDP, fixedGrowthLagTFP),file = "C:/Users/sec/Desktop/result.html",custom.model.names = c('GDP', 'GDP_LAG','TFP', 'TFP_LAG'),leading.zero = F,digits = 6)
